### ISSUE TITLE
Consolidated notification

### ISSUE THREAD

**Issue by matlag** [movim/movim_android#15]
Currently, we get one line of notification per event in Movim (new article, chat).
If you don't check your phone often, you end up with tens of notifications to clear out.

Besides, some notifications for new articles can come back several times.

It would be better if we had a single notification with an indication of how many events were recorded (a bit like most emails notification systems).

**Comment by edhelas** [comment]
The notification system will not be configured on the Android level.
Might happen one day on the Movim level.
