### ISSUE TITLE
Calls not working

### ISSUE THREAD

**Issue by elouin** [movim/movim_android#17]
Calls arent working. I only get a black screen with a "Play Button" in the middle, when trying to call someone. Incoming calls arent shown.

**Comment by testbird** [comment]
The easiest stop-gap solution might be adding the trivial [support for generating ad-hoc links](https://support.delta.chat/t/webrtc-for-communicating/410/13), which should even work without building the app with anything like the [jitsi-meet SDK](https://github.com/jitsi/jitsi-meet).

**Comment by edhelas** [comment]
Calls were refactored heavily those past years, feel free to try again :)
