### ISSUE TITLE
Cannot connect to my account using app

### ISSUE THREAD

**Issue by simbelmas** [movim/movim_android#18]
Using Movim app from fdroid or google play.
After pod choice and credential validation, the app shows public profile popup, then disconnects with following error message : "To protect your information from being stolen, Movim has not connected to this website."

I tried on wifi/data and with/out openvpn.
I'm runnig lineage os 14.1 (android 7.1.2)

Add : i have a contact wich hosts his own ejaboerd/movim instance. When i remove him from my contact list, the app stay connected

**Comment by edhelas** [comment]
This is a http/https protection system that was triggered, some work has been done in the app to protect content that is loaded from unprotected sources. Can you please try again?
