### ISSUE TITLE
Can't send file

### ISSUE THREAD

**Issue by Nyco** [movim/movim_android#2]
GIVEN I am in a conversation adn I have clicked on the clipper icon (send file)
WHEN I click on the "Choose file" button
THEN I should have the file picker opened
BUT the file picker is not opened

![b00a181b3c4745aba71c0b23bdcbb9aa](https://cloud.githubusercontent.com/assets/25348/12913695/8c9e43ec-cf20-11e5-84a8-1fff273de218.jpg)

Also, the "No file selected" should be properly displayed. Minor.

**Comment by edhelas** [comment]
Fixed in pull request #10
