### ISSUE TITLE
decentralized, local instance build?

### ISSUE THREAD

**Issue by testbird** [movim/movim_android#24]
I had expected the android app would run and display a local movim instance, and only connect to the XMPP server for the message exchange.

Apparently, the current implementation requires all users to give their XMPP account credentials away to some movim "pod", which is not very desirable. Would it be possible to solve this by letting the movin "apps" run their own (decentral) instances.

**Comment by edhelas** [comment]
Movim is running on a server. The Movim android app is basically a webview to a Movim pod.
