### ISSUE TITLE
Improve the Configuration area

### ISSUE THREAD

**Issue by Kohoshi12** [movim/movim_android#32]
![Imagepipe_0](https://user-images.githubusercontent.com/74657968/107605372-53096f00-6c76-11eb-8b5e-43bd180b9572.jpg)
The configuration's icon used twice, first on the left panel used for a lot of things for the user, second on the configuration area. The icon doesn't need to be in this area, because the user already know they are in the configuration area and because Help area doesn't use the same icon twice as well, and the icon is clickable for some reason. 

![Imagepipe_1](https://user-images.githubusercontent.com/74657968/107605685-3de11000-6c77-11eb-9cce-785865922d1e.jpg)
The name "configuration" of this area may confuse the user, the name should be "General" as this area already suggests or "Appearence" or "Behavior".

**Comment by edhelas** [comment]
The header has been removed in the app :)
