### ISSUE TITLE
Q: dead/abandonded repo? movim_android

### ISSUE THREAD

**Issue by jwmh** [movim/movim_android#41]
Havent seen any issues closed here in several months.

**Comment by edhelas** [comment]
Yes you're right. As explained there I was looking for a maintainer for the Android app: https://mov.im/?node/pubsub.movim.eu/Movim/we-are-looking-for-some-help-for-the-movim-android-application-DLkLBJ

As I don't have time to maintain this one I'll archive the repository. 
I am planning to make Movim a PWA to allow easy install on mobile phones and (at least) have some basic features on mobile.
