### ISSUE TITLE
Movim client 0.9 on Android 4.4

### ISSUE THREAD

**Issue by wint3** [movim/movim_android#7]
The UI seems a bit laggy. When I write a post and make it public, clicking on "public URL for this post" takes me to the Movim website itself within the app. Then the back button stops working. Clicking on links work. But cannot go back.
Device: Xiaomi Redmi 2 prime. MIUI version 7.0.9 Global. Running KitKat 4.4.

**Comment by edhelas** [comment]
Merge with #1, but it will be a wontfix
