### ISSUE TITLE
Provide network bootstrapping

### ISSUE THREAD

**Issue by nicorikken** [movim/movim_android#8]
As a newcomer to Movim, I started from the Android app, via F-Droid. Having set up my account (newly created, very nice :+1:) it becomes apparent that I'm out of luck, as I do not now anybody using Movim (yet :wink:)

Please provide some network bootstrapping functionality. Some thoughts:
- Allow a user to read the Contacts on the device and check if Movim accounts are registered for these users.
- Show a list of public groups.
- Offer to join a Movim Android group to discuss its awesomeness and possible improvements.
- Offer a default group for (Android) newcomers to say hi and have a Movim sandbox.

If I overlooked already existing functionality, please make that more upfront.
If this is better scoped at the main repo, please link or copy.

**Comment by edhelas** [comment]
Thanks for the feedback.
- For the first item of the list, it will be a simple no. Reading user contacts, uploading them to a server and filter the user accounts is clearly a privacy issue and cannot be done technically without centralization and full trust in the centralized platform.
- For the second item. There is already a list of public groups if you use Movim on a tablet or a desktop (page Groups, second column).
- For the third one, it's planned to have "sharing" features for the 0.9.2 release.
- For the fourth one, I'll think of it.

Regards.

**Comment by nicorikken** [comment]
Thanks for the info. I'll try out on my desktop then. Mobile use (both browser and app) didn't bring me anywhere. Getting it exposed in the app would be nice.
Regarding the first issue. Of course that would be a very evil implementation. I was thinking of a client-side solution, like looking for similar names, or registered id's like email or Twitter handles. I saw Movim offers a method for publicly listing such details.

**Comment by nicorikken** [comment]
I just noted the Movim chatroom is listed on the main Movim webpage 👍

**Comment by nicorikken** [comment]
Now I see the feature is actually there on the website, after finally having logged in using a laptop web browser. If only this was available on in the Android client. And it is present for all the major content types 👍 (so the feature itself actually is very nice).
**When I open up the option to create a post, I see the introduction screen flash briefly, so it seems the content is actually available in the client (just webview I assume).**
So can a logical option be provided to expose the current bootstrapping content to the user? Like say be swiping in from the right, or having an additional round icon in the bottom to open the bootstrapping screen?
